# Generated by Django 4.1 on 2022-09-17 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indexform', '0008_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['-name'],
            },
        ),
    ]
