# Generated by Django 4.0.6 on 2022-09-18 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('indexform', '0010_author_blog_entry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entry',
            name='authors',
            field=models.ManyToManyField(null=True, to='indexform.author'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog', to='indexform.blog'),
        ),
        migrations.AlterField(
            model_name='entry',
            name='headline',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
